baseurl = "/"
languageCode = "en-us"
title = "Telematique StatusKit"

[permalinks]
  incidents = "/incidents/:year/:month/:day/:slug/"

[params]
  defaultLogo = "https://www.netlify.com/img/press/logos/logomark.svg"
  faviconsPath = "/images/favicon/"

# List of systems monitored in this status page.
# You'll be able to change their status every time
# you open or update an incident.
# Example:
# systems = ["API", "CDN", "DNS", "Site delivery"]
systems = ["DNS", "NAS", "PMS"]
